services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: R1234r
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: clarusway
      MYSQL_PASSWORD: Clarusway_1
    
    networks:
      - booknet
    
    volumes:
      - bookvolumes:/var/lib/mysql
  
  myapp: 
    build: .
    restart: always
    depends_on:
      - database
    ports:
      - "80:80"
    networks:
      - booknet
networks:
  booknet:
    driver: bridge
volumes:
  bookvolumes: