apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql-pods
  template:
    metadata:
      labels:
        app: mysql-pods
    spec:
      containers:
        - image: mysql:5.7
          name: mysql
          envFrom:
            - secretRef:
                name: mysql-secret
            - configMapRef:
                name: mysql-config

          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_USER: clarus
  MYSQL_DATABASE: phonebook

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: UGwxMjM0NTY=
  MYSQL_PASSWORD: Q2xhcnVzd2F5XzE=

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-deploy
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-pods
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
